<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <base href="<?php echo url::base();?>" />
    <title>Photo Tagging Application</title>
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <link rel="stylesheet" href="css/themes/base/jquery.ui.all.css">
    <link rel="stylesheet" href="css/demos.css">
    
    <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/phototagging.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.core.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.widget.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.mouse.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.resizable.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.draggable.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.position.min.js"></script>
    <script type="text/javascript" src="js/ui/jquery.ui.autocomplete.min.js"></script>
</head>
<body>
<div id="container">
    <div id="nav">
        <h1>Photo Tagging Application</h1>
        <ul>
            <li><a href="index.php/welcome/">Upload an image</a></li>
            <li><a href="index.php/welcome/list/">Tag list</a></li>
            <li><a href="index.php/welcome/images/">Image list</a></li>
        </ul>
    </div>
    <div id="content">
